
development:
  adapter: postgresql
  encoding: unicode
  database: fantasygolf_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fantasygolf_test
  pool: 5
  host: localhost
